FROM scratch

ADD metadata/   /metadata/
ADD manifests/  /manifests/

!!ANNOTATION_LABELS!!

LABEL com.redhat.delivery.operator.bundle=true
LABEL com.redhat.openshift.versions="!!OCP_VERSIONS!!"
LABEL com.redhat.delivery.backport=false

