FROM scratch

# This ADD line set up the only content of this image.

ADD manifests/  /manifests/

# This label tells the delivery pipeline to process this as operator
# metadata in the App Registry format.

LABEL com.redhat.delivery.appregistry=true
