apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion": "operators.open-cluster-management.io/v1beta1", "kind": "MultiClusterHub",
      "metadata": {"name": "multiclusterhub", "namespace": "open-cluster-management"}, "spec": {"imagePullSecret":
      "quay-secret"}}]'
    capabilities: Basic Install
    categories: Integration & Delivery
    certified: 'false'
    support: The Open Cluster Management Project
    createdAt: '2020-05-05T11:21:40Z'
    description: Open management of Openshift and Kubernetes clusters
  name: open-cluster-management-hub.v1.0.0
  namespace: placeholder
spec:
  displayName: Open Cluster Management Hub
  version: 1.0.0
  provider:
    name: Red Hat
  maintainers:
  - email: ocm-dev@open-cluster-management.io
    name: Open Cluster Management Project team
  maturity: alpha
  description: 'The Open Cluster Management Hub operator installs and maintains an instnace

    of the OCM hub, a cetneral management console for managing OpenShift and

    Kubernetes clusters.

    '
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAABmJLR0QA/wD/AP+gvaeTAAAEDElEQVRoge2ZSWgUQRSGv0lmXKLiAm4RRTAqmCDoUUVBjYKKIMZ49C6auB3Ei548uBy8RNCTSkAwiKAgiDkIKoLoQY1L3EHNwV1jNDGZ8VCvrJ6eXqqT7nEi+aHo7nqvuv6/6/XrVzMwhCEkghSQleNgQgHfsn/BIgmkHeeDbVXy8F+uiEau6CwGhhT85yuiUervTF7keK3IYAstIFjIQUp3VZZ5dWbJXwV9nQPOASOT5xUJdcBPDMe/cAvpk+tvcrwGTCgOx1DsI/9BWwmZD7yW86fA7GIw9UE50CRceoEGIggpAyqBO3L9AVicOOVCjAYuCYefQL30hwrpxQgJulExMBX/B2ktpNzRVw4cxyzt9tgpF6KG4NDulxCNRkzoHSO5ymAF8EXmuQlM9PAJFfIbfyEAmzDp7zxQMSDKhdgC9Mj9W/BP/9ZCgsqXRcB78bsFTOoX5XykgAMOPmErHosQgCpU7OaA58DcCKTdSAMnMO/gVosxoUL0soYJAZgC3Bb/j8BSizFujAEuyz06gXWW40KFdMt1xvKGk4HPmPS8yXIcwAzgvox9ByyMMDZWIbMdRH7JsQ/YYzF2AfBWxjxAiYqC2ISsAT6J72NgHvnp+ST+4VkLfBW/VmBcFAWCUCH6yQ7zuUEZKrtowi2oONdwpuerwCyHrQLYj0kopwLmCcOAhIwDLmKyy1689yyLgA6H3z3gBqai7hNBA9nvWAsZ7hpYA7Rj6p7akIkmosJL30+36/hntwywGWhGpfZO4AcqvTejVluHa6gQHRZOIfXAd+m/C8wMEeFEBarYWw5MC/DbIIRzIe0FsDaqkDRw2OFzmvh3jCngqIPYA2AHUA2MklYN7ATaPISFCpmOyig51EdyW8wCNI7IHN0yh1+Nh9gaMB/tQCFdcv1Gjh3AkrhYu7AeI2Klh70VuODRX4sRs1Z3+gnJoTJNZSyUC5HB7De8Vjstti6f8Y1ifym+vkKa6H+Ot0Ed5p3wCqcwIWngofh4lkU/xBj3PsONszLPDh97mBCAXeLT7GXUQiqB8dKSEPVE5pnnY7cRUiM+z7yMWkixmi5vrgT49KDqOt3OyZgxYu/0Kuo+o7KIE2XA2IAnEweCVj2DigyNKpc9Gz8de+jQqnb0jXc1XZtNcfXr5KBD67HNLjAp3AXmAKtQX2xQ0eCEzqZfUDWbG6vleDt2dhGwEUW0Df+vud6zjPCwpYFHYq9LgqAtMsArIdLg4xMkZKfY2rHflieGdZis5LUtaEXtZdz7llUyJosqc0oChzBiGgn+9SaNWgldZx1MnF0EpMjfKrShvtg1qB/QR8v5bkxJkkWJKMk/c9djfvALau2UUDj5IY0qAM+gvjOdqJ3pQ+mrowRe7CHY4A8ixrhAvKZDJwAAAABJRU5ErkJggg==
    mediatype: image/png
  keywords:
  - Red Hat
  - cluster
  - kubernetes
  - multi-cluster
  - multicluster
  - openshift
  labels:
    app: ocm-hub
  links:
  - name: Documentation
    url: https://github.com/open-cluster-management/acm/start-here.html
  selector:
    matchLabels:
      app: ocm-hub
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  customresourcedefinitions:
    owned:
    - name: multiclusterhubs.operators.open-cluster-management.io
      group: operators.open-cluster-management.io
      kind: MultiClusterHub
      version: v1beta1
      displayName: MultiClusterHub
      description: MultiClusterHub defines the configuration for an instance of the MultiCluster Hub
    required:
    - name: helmreleases.apps.open-cluster-management.io
      version: v1
      kind: HelmRelease
      displayName: Helm Release
      description: Represent a helm chart selected by the subscription, for internal use only.
    - name: hiveconfigs.hive.openshift.io
      version: v1
      kind: HiveConfig
      displayName: Hive Config
      description: Configuration for the Hive Operator
    - name: etcdclusters.etcd.database.coreos.com
      version: v1beta2
      kind: EtcdCluster
      displayName: etcd Cluster
      description: Represents a cluster of etcd nodes.
    - name: subscriptions.apps.open-cluster-management.io
      version: v1
      kind: Subscription
      displayName: Subscription
      description: Subscribe resources from a channel according to its package filters
    - name: channels.apps.open-cluster-management.io
      version: v1
      kind: Channel
      displayName: Channel
      description: Represent a helm chart repository
  install:
    strategy: deployment
    spec:
      clusterPermissions:
      - serviceAccountName: multiclusterhub-operator
        rules:
        - apiGroups:
          - ''
          resources:
          - pods
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - serviceaccounts
          - namespaces
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - multiclusterhub-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - ''
          resources:
          - pods
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - replicasets
          - deployments
          verbs:
          - get
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - operators.open-cluster-management.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - apiregistration.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - clusterregistry.k8s.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - operators.coreos.com
          resources:
          - operatorgroups
          - subscriptions
          verbs:
          - get
          - create
        - apiGroups:
          - etcd.database.coreos.com
          resources:
          - etcdclusters
          verbs:
          - get
          - create
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - '*'
        - apiGroups:
          - apps.open-cluster-management.io
          resources:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - operators.coreos.com
          resources:
          - hive-catalog
          - catalogsources
          - clusterserviceversions
          - hiveconfig
          verbs:
          - get
          - create
        - apiGroups:
          - hive.openshift.io
          resources:
          - hiveconfigs
          verbs:
          - get
          - create
          - list
          - delete
        - apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          verbs:
          - '*'
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - '*'
        - apiGroups:
          - config.openshift.io
          resources:
          - ingresses
          verbs:
          - get
      deployments:
      - name: multiclusterhub-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: multiclusterhub-operator
          template:
            metadata:
              labels:
                name: multiclusterhub-operator
            spec:
              serviceAccountName: multiclusterhub-operator
              imagePullSecrets:
              - name: multiclusterhub-operator-pull-secret
              containers:
              - name: multiclusterhub-operator
                image: multiclusterhub-operator:1.0.0
                imagePullPolicy: Always
                command:
                - multiclusterhub-operator
                resources:
                  requests:
                    memory: 256Mi
                    cpu: 100m
                  limits:
                    memory: 2048Mi
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: OPERATOR_NAME
                  value: multiclusterhub-operator
                - name: USER
                  value: multiclusterhub-operator
                - name: TEMPLATES_PATH
                  value: /usr/local/templates
